#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_symphony = env_modules.Clone()

env_symphony.add_source_files(env.modules_sources, "*.cpp")
env_symphony.add_source_files(env.modules_sources, "core/*.cpp")
env_symphony.add_source_files(env.modules_sources, "stream/*.cpp")
env_symphony.add_source_files(env.modules_sources, "nodes/generators/*.cpp")
env_symphony.add_source_files(env.modules_sources, "nodes/envelopes/*.cpp")
env_symphony.add_source_files(env.modules_sources, "nodes/io/*.cpp")
